import './workspace.css';
import * as T from 'three';
import { createStudio } from './scene.js';
import { HOME, LIMITS, SPEEDS, forward, pose, solve } from './kinematics.js';
import { createViewCube } from './view-cube.js';
import { iconButton, displayControls } from './icons.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const base=import.meta.env.BASE_URL;
const app=$('#app');
app.innerHTML=`<div class="app">
<header class="top"><span class="brand">ENCY HYPER <span class="brand-divider">-</span> <span class="brand-model">ESTUN</span></span></header>
<main class="workspace"><div class="viewport" id="viewport"></div>
<section class="panel prep" aria-label="Weld preparation"><div class="panel-header"><h2>Weld preparation</h2></div><div class="form stack">
<div class="row equal"><button id="import">Import STEP</button><button id="sample">Load sample</button></div><input type="file" id="file" accept=".step,.stp" hidden><div class="file-name" id="file-name">No workpiece loaded</div><hr>
<h3>Part placement</h3><div class="row equal"><button id="move" class="active">Move · W</button><button id="rotate">Rotate · E</button></div>
<div class="coordinates"><span></span><span class="small muted">Position · mm</span><span class="small muted">Rotation · °</span>${['X','Y','Z'].map((axis,i)=>`<label>${axis}</label><input aria-label="Part ${axis} position in millimeters" id="pos-${i}" type="number" min="-10000" max="10000" value="0" step="1"><input aria-label="Part ${axis} rotation in degrees" id="rot-${i}" type="number" min="-360" max="360" value="0" step="1">`).join('')}</div><hr>
<h3>Seam detection</h3><div class="row"><input aria-label="Minimum seam angle" id="min-angle" type="number" min="0" max="180" value="85"><span class="muted">to</span><input aria-label="Maximum seam angle" id="max-angle" type="number" min="0" max="180" value="95"><span class="muted">°</span></div><label class="check"><input type="checkbox" id="concave" checked> Concave / contact only</label>
<div class="row spread"><span class="small muted" id="counts">No candidate seams</span><button id="restore">Restore</button></div><div class="seams" id="seams"><div class="empty">Import a STEP workpiece or load the sample to review weld seams.</div></div></div>
<div class="execution stack"><div class="progress" id="plan-progress"><span></span></div><button class="primary" id="generate">GENERATE PROGRAM</button><div class="row equal"><button id="simulate">SIMULATE</button><button id="export">EXPORT</button></div></div></section>
<div class="center-ui"><div class="telemetry"><div class="motion" id="motion">STANDSTILL</div><div id="tcp">X 927.5 &nbsp; Y 650.3 &nbsp; Z −319.0</div></div><div class="viewcube" id="view-cube"></div>
<div class="toast hidden" id="toast" role="status"></div><nav class="icon-rail" aria-label="Viewport and display">
${iconButton('axes','axes','TCP coordinate axes',true)}${iconButton('trace','trace','TCP motion trace')}
<span class="rail-divider"></span>
${displayControls.map(([id,label])=>iconButton('setting-'+id,id,label,true)).join('')}
${iconButton('exposure-button','exposure','Exposure')}${iconButton('resolution-button','resolution','3D resolution')}${iconButton('reset-display','reset','Reset display to crisp')}
</nav>
<section id="exposure-popover" class="control-popover" popover aria-label="Exposure"><label for="exposure">Exposure <output id="exposure-value">0.92</output></label><input type="range" id="exposure" min=".4" max="1.8" step=".01" value=".92"></section>
<section id="resolution-popover" class="control-popover" popover aria-label="3D resolution"><label for="resolution">3D resolution</label><select id="resolution"><option value="1">Native · 100%</option><option value=".75">Balanced · 75%</option><option value=".5">Performance · 50%</option></select></section></div>
<aside class="pendant-dock" aria-label="Teach pendant"><div class="pendant"><i class="screw tl"></i><i class="screw tr"></i><i class="screw bl"></i><i class="screw br"></i><div class="pendant-head"><div><div class="pendant-brand">ESTUN<small>TEACH PENDANT</small></div><div class="model">S20-180 PRO</div></div><button class="estop" id="estop" aria-label="Emergency stop">↷<br>STOP</button></div>
<div class="lcd"><div class="row spread small muted"><span id="drive-status">Drives off</span><span>T1 / MANUAL</span></div><div class="row modes">${['JOINT','WORLD','TOOL'].map((m,i)=>`<button class="${i?'':'active'}" data-mode="${m}">${m}</button>`).join('')}</div><div class="small muted" id="axis-caption">Axis position · degrees</div>
${Array.from({length:6},(_,i)=>`<div class="axis-row ${i?'':'selected'}" data-axis="${i}"><div class="axis-value"><span class="axis-label">J${i+1}</span><span class="value" id="joint-${i}">0.00</span><span class="unit">°</span></div><button class="jog" data-axis="${i}" data-dir="-1" aria-label="Jog axis ${i+1} negative">−</button><button class="jog" data-axis="${i}" data-dir="1" aria-label="Jog axis ${i+1} positive">+</button></div>`).join('')}
<div class="row spread" style="margin-top:9px"><span class="small muted">Speed override</span><span id="speed-value">25%</span></div><input aria-label="Speed override" id="speed" type="range" min="1" max="100" value="25"></div>
<div class="hardware stack"><div class="row equal"><button class="hardware-key" id="drives">DRIVES OFF</button><button class="hardware-key" id="stop">STOP MOTION</button></div><div class="row spread small muted"><span>Motion program</span><span id="point-count">0 points</span></div><div class="key-grid"><button class="hardware-key" id="home">HOME</button><button class="hardware-key" id="record">REC</button><button class="hardware-key" id="run">RUN</button><button class="hardware-key" id="reset">RESET</button></div></div><div class="pendant-foot">SPACE STOP · ESC E-STOP</div></div></aside>
<div class="loading" id="loading"><img src="${base}assets/icon.svg" alt=""><h2>ENCY HYPER - ESTUN</h2><div class="small" id="loading-text">Loading original S20-180 Pro geometry…</div><div class="progress"><span id="load-progress"></span></div></div></main>
<footer class="footer"><span id="status">S20-180 Pro · Offline simulator · Space stops motion</span><span id="fps">WebGL 2 · Native</span></footer>
</div>
<dialog id="program"><div class="row spread"><h2>Taught positions</h2><button class="close" data-close aria-label="Close program">×</button></div><div class="body"><div class="points" id="points"></div><div class="row equal"><button id="save-points">Save</button><button id="load-points">Load</button><button id="clear-points">Clear</button></div><p class="small">Joint motion between recorded positions. Taught motion is not collision checked. Welding paths are generated separately.</p></div></dialog>
<dialog id="export-dialog"><div class="row spread"><h2>Export welding program</h2><button class="close" data-close aria-label="Close export">×</button></div><div class="body"><p>Joint angles, TCP poses, timing, arc state and validation metadata.</p><div class="row equal"><button id="export-json">JSON</button><button id="export-csv">CSV</button></div><p class="small">Offline trajectory representation. Controller-ready NC code requires a postprocessor and calibrated cell.</p></div></dialog>
<dialog id="help"><div class="row spread"><h2>Workspace guide</h2><button class="close" data-close aria-label="Close help">×</button></div><div class="body"><h3>Prepare</h3><p>Import STEP or load the sample. Move / W and Rotate / E position the workpiece. Select seams in the list or 3D view, exclude unwanted candidates, then generate a program.</p><h3>Operate</h3><p>Enable DRIVES. Hold −/+ to jog. HOME, RUN and SIMULATE start with one click. Space stops motion; Escape latches emergency stop. RESET clears the latch and leaves drives off.</p><h3>Navigate</h3><p>Drag to orbit, middle-drag to pan, wheel to zoom. F fits the cell. P hides the pendant. Tab opens cinema; Tab again restores controls.</p><h3>Planning</h3><p>STEP recognition and collision planning use the original OpenCascade / C# core. Green means this planner found a sampled checked trajectory; red means it found no path. This is an offline simulator with no connection to robot hardware.</p></div></dialog>`;

let studio,viewCube,selectedScroll=false,angles=HOME.slice(),drives=false,estop=false,mode='JOINT',selectedAxis=0,speed=.25,jog=null,motion=null,doc=null,partName='',selectedSeam=null,deleted=new Set(),result=null,busy=false,jobId=null,revision=0,toastTimer,points=[],cinema=false,arc=false;
const settingsDefaults={shadows:true,ao:true,bloom:true,sparks:true,smoke:true,beads:true,exposure:.92,resolution:1};let settings={...settingsDefaults};
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
function status(text){$('#status').textContent=text;}
function stop(reason,invalid=false){const wasPlanned=motion?.type==='weld';jog=null;motion=null;arc=false;studio?.setArc(false);$('#simulate').textContent='SIMULATE';if(wasPlanned&&(invalid||reason)){result=null;refreshSeams();status('Motion stopped · generate again from the current pose');}if(reason)toast(reason);}
function canMove(){if(busy){toast('Wait for the current operation to finish');return false;}if(estop){toast('Reset emergency stop first');return false;}if(!drives){toast('Enable DRIVES first');return false;}return true;}
function driveUI(){$('#drives').textContent=drives?'DRIVES ON':'DRIVES OFF';$('#drives').classList.toggle('enabled',drives);$('#drive-status').textContent=estop?'EMERGENCY STOP':drives?'Drives on':'Drives off';$('#estop').classList.toggle('latched',estop);}
function invalidate(){revision++;result=null;stop();studio?.clearEffects();refreshSeams();status('Workpiece changed · generate a new program');}
function getCandidates(){if(!doc)return [];const min=Number($('#min-angle').value),max=Number($('#max-angle').value),concave=$('#concave').checked;return doc.seams.filter(s=>!deleted.has(s.id)&&s.minAngleDegrees>=min-.05&&s.maxAngleDegrees<=max+.05&&(!concave||s.concave||s.kind.toLowerCase().includes('contact')));}
function refreshSeams(){if(!doc)return;const list=getCandidates();$('#counts').textContent=`${list.length} seams / ${deleted.size} excluded`;const container=$('#seams');const previousScroll=container.scrollTop;container.replaceChildren();for(const s of list){let len=0;for(let i=3;i<s.points.length;i+=3)len+=Math.hypot(...s.points.slice(i,i+3).map((v,k)=>v-s.points[i-3+k]));const r=result?.program.seams.find(r=>r.id===s.id),row=document.createElement('div');row.className='seam-row';const btn=document.createElement('button');btn.textContent=`${s.id} · ${(len*1000).toFixed(0)} mm · ${s.angleDegrees.toFixed(0)}°`;btn.classList.toggle('selected',s.id===selectedSeam);if(r)btn.classList.add(r.state==='Ready'?'ready':'blocked');btn.title=r?.Reason||r?.reason||s.kind;btn.onclick=()=>selectSeam(s.id);const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label',`Exclude seam ${s.id}`);remove.onclick=()=>{if(busy)return;deleted.add(s.id);invalidate();};row.append(btn,remove);container.append(row);}if(!list.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='No seams match the current filters.';container.append(empty);}container.scrollTop=previousScroll;if(selectedScroll){const selected=container.querySelector('.selected');if(selected){const row=selected.parentElement;if(row.offsetTop<container.scrollTop)container.scrollTop=row.offsetTop;else if(row.offsetTop+row.offsetHeight>container.scrollTop+container.clientHeight)container.scrollTop=row.offsetTop+row.offsetHeight-container.clientHeight;}selectedScroll=false;}studio?.seams(list,result?.program.seams,selectedSeam);}
function selectSeam(id){selectedSeam=id;selectedScroll=true;refreshSeams();}
function syncPart(){for(let i=0;i<3;i++){$(`#pos-${i}`).value=(studio.part.position.getComponent(i)*1000).toFixed(1);$(`#rot-${i}`).value=T.MathUtils.radToDeg(studio.part.rotation.toArray()[i]).toFixed(1);}}
function acceptDocument(data,name){doc=data;partName=name;deleted.clear();selectedSeam=null;studio.loadPart(data);syncPart();invalidate();$('#file-name').textContent=`${name} · STEP`;$('#file-name').title=`${data.solidCount} solids · ${data.indices.length/3} triangles`;toast(`STEP imported · ${data.solidCount} solids · ${(data.indices.length/3).toLocaleString()} triangles`);if(data.warnings?.length)status(`Import notes · ${data.warnings.join(' · ')}`);}
function setBusy(value){busy=value;for(const s of ['#import','#sample','#restore','#min-angle','#max-angle','#concave',...Array.from({length:3},(_,i)=>`#pos-${i}`),...Array.from({length:3},(_,i)=>`#rot-${i}`)])$(s).disabled=value;studio?.setGizmo(!value&&!!doc&&!$('.app').classList.contains('hide-prep'));}
async function api(path,options={}){const response=await fetch(`${base}api/${path}`,options);const body=await response.json().catch(()=>({error:`Server returned ${response.status}`}));if(!response.ok)throw Error(body.error||body.message||`Request failed (${response.status})`);return body;}
async function loadSample(){if(busy)return;stop();setBusy(true);try{const r=await fetch(`${base}assets/sample.json`);if(!r.ok)throw Error('Sample could not be loaded');acceptDocument(await r.json(),'WeldingBracket');}catch(e){toast(e.message);}finally{setBusy(false);}}
async function generate(){if(busy){if(jobId){await api(`planner/jobs/${jobId}`,{method:'DELETE'}).catch(e=>toast(e.message));}return;}if(!doc){toast('Import a STEP workpiece first');return;}if(!getCandidates().length){toast('No seams in the selected range');return;}stop();result=null;refreshSeams();studio.clearEffects();setBusy(true);$('#generate').textContent='CANCEL PLANNING';const snapshot=revision;
  try{const response=await api('planner/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:doc,partName,partTransform:{position:[studio.part.position.x,studio.part.position.y-.12,studio.part.position.z],quaternion:studio.part.quaternion.toArray()},startAngles:angles,seamIds:getCandidates().map(s=>s.id)})});jobId=response.jobId;
    for(;;){await new Promise(r=>setTimeout(r,800));const job=await api(`planner/jobs/${jobId}`);$('#plan-progress span').style.width=`${Math.max(0,Math.min(1,job.progress||0))*100}%`;status(job.message||'Planning collision-checked trajectories…');if(job.status==='complete'){if(snapshot===revision){result=job.result;refreshSeams();status(result.summary);toast(result.summary);}break;}if(job.status==='failed')throw Error(job.error||job.message||'Planning failed');if(job.status==='cancelled'){status('Planning cancelled');break;}}
  }catch(e){toast(e.message);status(`Planning unavailable · ${e.message}`);}finally{jobId=null;setBusy(false);$('#generate').textContent='GENERATE PROGRAM';}
}
function startSimulation(){if(motion?.type==='weld'){stop('Simulation stopped',true);return;}if(!canMove())return;if(!result?.program.moves.length){toast('Generate a program with reachable seams first');return;}const start=result.program.startJoints||result.program.startAngles||result.program.StartAngles;if(!start||Math.max(...angles.map((a,i)=>Math.abs(a-start[i])))>.3){toast('Robot start pose changed · generate again');result=null;refreshSeams();return;}studio.clearEffects();motion={type:'weld',index:0,elapsed:0,start:angles.slice(),moves:result.program.moves};$('#simulate').textContent='STOP';status('Running checked welding trajectory');}
function startJog(axis,dir){if(!canMove())return;stop();if(result){result=null;refreshSeams();}jog={axis,dir};selectedAxis=axis;selectAxis();}
function selectAxis(){$$('.axis-row').forEach((el,i)=>el.classList.toggle('selected',i===selectedAxis));}
function setMode(value){stop();mode=value;$$('[data-mode]').forEach(el=>el.classList.toggle('active',el.dataset.mode===mode));$('#axis-caption').textContent=mode==='JOINT'?'Axis position · degrees':'TCP position · mm / degrees';$$('.axis-row').forEach((el,i)=>{el.querySelector('.axis-label').textContent=mode==='JOINT'?`J${i+1}`:'XYZABC'[i];el.querySelector('.unit').textContent=mode==='JOINT'||i>2?'°':'mm';});}
function setGizmo(mode){studio.setMode(mode);$('#move').classList.toggle('active',mode==='translate');$('#rotate').classList.toggle('active',mode==='rotate');}
function toggleDock(which){stop();const root=$('.app');root.classList.toggle(`hide-${which}`);if(innerWidth<850&&!root.classList.contains(`hide-${which}`))root.classList.add(`hide-${which==='prep'?'pendant':'prep'}`);studio.setGizmo(!!doc&&!root.classList.contains('hide-prep')&&!busy);}
function updatePoints(){$('#point-count').textContent=`${points.length} points`;const box=$('#points');box.replaceChildren();if(!points.length){const e=document.createElement('p');e.textContent='No points recorded. Use REC on the pendant.';box.append(e);}points.forEach((p,i)=>{const e=document.createElement('div');e.className='point';const label=document.createElement('span');label.textContent=`P${String(i+1).padStart(3,'0')} · Joint motion`;const val=document.createElement('span');val.className='muted';val.textContent=`${Math.round(p.speed*100)}%`;e.append(label,val);box.append(e);});}
function download(data,name,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setDisplay(){for(const [k] of displayControls){const button=$(`#setting-${k}`);button.classList.toggle('active',settings[k]);button.setAttribute('aria-pressed',String(settings[k]));}$('#exposure').value=settings.exposure;$('#exposure-value').textContent=Number(settings.exposure).toFixed(2);$('#exposure-button').title=`Exposure · ${Number(settings.exposure).toFixed(2)}`;$('#resolution').value=settings.resolution;$('#resolution-button').title=`3D resolution · ${Math.round(settings.resolution*100)}%`;studio?.applySettings(settings);try{localStorage.setItem('estun-web-display',JSON.stringify(settings));}catch{}}
function emergency(){stop('Emergency stop latched');estop=true;drives=false;driveUI();}
$$('[data-dialog]').forEach(b=>b.onclick=()=>{stop();updatePoints();$('#'+b.dataset.dialog).showModal();});$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||busy)return;if(file.size>64*1024*1024){toast('Browser import limit: 64 MB');return;}stop();setBusy(true);status('Reading STEP with OpenCascade…');try{const data=new FormData();data.append('file',file);const raw=await api('import',{method:'POST',body:data});acceptDocument(raw.document,raw.name);}catch(error){toast(error.message);status(`Import failed · ${error.message}`);}finally{setBusy(false);}};
$('#sample').onclick=loadSample;$('#generate').onclick=generate;$('#simulate').onclick=startSimulation;
$('#move').onclick=()=>setGizmo('translate');$('#rotate').onclick=()=>setGizmo('rotate');
for(let i=0;i<3;i++)for(const kind of ['pos','rot'])$(`#${kind}-${i}`).onchange=e=>{if(!doc||busy)return;const v=Number(e.target.value),limit=kind==='pos'?10000:360;if(!Number.isFinite(v)||Math.abs(v)>limit){syncPart();return;}if(kind==='pos')studio.part.position.setComponent(i,v*.001);else{const r=studio.part.rotation.toArray();r[i]=T.MathUtils.degToRad(v);studio.part.rotation.fromArray(r);}invalidate();};
for(const id of ['min-angle','max-angle','concave'])$('#'+id).onchange=()=>{if(+$('#min-angle').value>+$('#max-angle').value){toast('Minimum angle must be less than maximum');return;}invalidate();};$('#restore').onclick=()=>{deleted.clear();invalidate();};
$('#drives').onclick=()=>{if(estop){toast('Reset emergency stop first');return;}drives=!drives;if(!drives)stop('Drives off');driveUI();};$('#estop').onclick=emergency;$('#reset').onclick=()=>{stop();estop=false;drives=false;driveUI();toast('Emergency stop reset · drives off');};$('#stop').onclick=()=>stop('Motion stopped');
$('#home').onclick=()=>{if(!canMove())return;stop();result=null;refreshSeams();motion={type:'taught',index:0,elapsed:0,start:angles.slice(),moves:[{joints:HOME.slice(),duration:Math.max(.4,...angles.map((a,i)=>Math.abs(a-HOME[i])/SPEEDS[i]))}]};};
$('#record').onclick=()=>{if(busy)return;points.push({angles:angles.slice(),speed});updatePoints();toast(`Recorded P${String(points.length).padStart(3,'0')}`);};
$('#run').onclick=()=>{if(!canMove())return;if(!points.length){toast('Record positions first');return;}stop();result=null;refreshSeams();let prev=angles;const moves=points.map(p=>{const move={joints:p.angles,duration:Math.max(.25,...prev.map((a,i)=>Math.abs(a-p.angles[i])/SPEEDS[i]))/p.speed};prev=p.angles;return move;});motion={type:'taught',index:0,elapsed:0,start:angles.slice(),moves};status('Taught joint program · no collision validation');};
$('#speed').oninput=e=>{speed=Number(e.target.value)/100;$('#speed-value').textContent=`${Math.round(speed*100)}%`;};
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('.axis-value').forEach((el,i)=>el.onclick=()=>{selectedAxis=i;selectAxis();});
$$('.jog').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);startJog(Number(b.dataset.axis),Number(b.dataset.dir));};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{jog=null;};});
$('#save-points').onclick=()=>{try{localStorage.setItem('estun-web-waypoints',JSON.stringify(points));toast('Taught positions saved in this browser');}catch{toast('Browser storage is unavailable');}};$('#load-points').onclick=()=>{try{const p=JSON.parse(localStorage.getItem('estun-web-waypoints')||'[]');if(!Array.isArray(p)||p.length>1000||p.some(v=>!Array.isArray(v.angles)||v.angles.length!==6||v.angles.some((a,i)=>!Number.isFinite(a)||Math.abs(a)>LIMITS[i])||!Number.isFinite(v.speed)||v.speed<=0||v.speed>1))throw Error();points=p;updatePoints();toast('Taught positions loaded');}catch{toast('Saved positions could not be loaded');}};$('#clear-points').onclick=()=>{points=[];updatePoints();};
$('#export').onclick=()=>{if(!result){toast('Generate a welding program first');return;}$('#export-dialog').showModal();};$('#export-json').onclick=()=>{if(result)download(JSON.stringify(result.program,null,2),`${partName}-weld.json`);};$('#export-csv').onclick=()=>{if(result)download(result.csv,`${partName}-weld.csv`,'text/csv');};
for(const [id,method] of [['axes','setAxes'],['trace','setTrace']])$('#'+id).onclick=e=>{const button=e.currentTarget;button.classList.toggle('active');const active=button.classList.contains('active');button.setAttribute('aria-pressed',String(active));studio[method](active);};
for(const id of ['exposure','resolution']){
  const button=$('#'+id+'-button'),panel=$('#'+id+'-popover');button.onclick=()=>{const rect=button.getBoundingClientRect();panel.style.left=`${Math.max(8,Math.min(innerWidth-228,rect.right+8))}px`;panel.style.top=`${Math.max(8,Math.min(innerHeight-104,rect.top))}px`;panel.togglePopover();};
}
function toggleCinema(){stop();cinema=!cinema;$('.app').classList.toggle('cinema',cinema);studio.setGizmo(!cinema&&!!doc&&!busy&&!$('.app').classList.contains('hide-prep'));}
for(const [key] of displayControls)$(`#setting-${key}`).onclick=()=>{settings[key]=!settings[key];setDisplay();};$('#exposure').oninput=e=>{settings.exposure=+e.target.value;setDisplay();};$('#resolution').onchange=e=>{settings.resolution=+e.target.value;setDisplay();};$('#reset-display').onclick=()=>{settings={...settingsDefaults};setDisplay();};
window.addEventListener('blur',()=>stop(motion||jog?'Motion stopped · window lost focus':undefined));document.addEventListener('visibilitychange',()=>{if(document.hidden)stop(motion||jog?'Motion stopped · tab hidden':undefined);});
window.addEventListener('keydown',e=>{const edit=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(e.code==='Escape'){emergency();return;}if(edit||$('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();stop('Motion stopped');}if(e.repeat)return;if(e.code==='KeyF')studio?.fit();if(e.code==='KeyP')toggleDock('pendant');if(e.code==='KeyW')setGizmo('translate');if(e.code==='KeyE')setGizmo('rotate');if(e.code==='Tab'){e.preventDefault();toggleCinema();}if(e.code==='ArrowUp'||e.code==='ArrowDown'){e.preventDefault();selectedAxis=(selectedAxis+(e.code==='ArrowDown'?1:5))%6;selectAxis();}if(e.code==='ArrowLeft'||e.code==='ArrowRight'){e.preventDefault();startJog(selectedAxis,e.code==='ArrowRight'?1:-1);}if(e.code==='Delete'&&selectedSeam&&!busy){deleted.add(selectedSeam);invalidate();}});window.addEventListener('keyup',e=>{if(e.code==='ArrowLeft'||e.code==='ArrowRight')jog=null;});

let last=performance.now(),readout=0,frames=0,fpsTime=0;
function tick(now){const dt=Math.min((now-last)/1000,.05);last=now;
  if(jog&&drives&&!estop&&!busy){const {axis,dir}=jog;if(mode==='JOINT')angles[axis]=T.MathUtils.clamp(angles[axis]+dir*SPEEDS[axis]*speed*dt,-LIMITS[axis],LIMITS[axis]);else{const target=forward(angles),p=pose(target),direction=new T.Vector3().setComponent(axis%3,1),dp=axis<3?.25*speed*dt:0,da=axis>=3?Math.PI/3*speed*dt:0;if(mode==='TOOL')direction.applyQuaternion(p.quaternion);if(axis<3){p.position.addScaledVector(direction,dir*dp);target.setPosition(p.position);}else{p.quaternion.premultiply(new T.Quaternion().setFromAxisAngle(direction,dir*da));target.compose(p.position,p.quaternion,new T.Vector3(1,1,1));}const a=solve(target,angles,Math.max(.000015,dp*.12),Math.max(.00008,da*.12));if(a){let factor=1;for(let i=0;i<6;i++){const diff=Math.abs(a[i]-angles[i]);if(diff>1e-6)factor=Math.min(factor,SPEEDS[i]*speed*dt/diff);}if(factor>.015)angles=angles.map((v,i)=>v+(a[i]-v)*factor);else{jog=null;toast('TCP jog limited near singularity');}}else{jog=null;toast('TCP limit reached · pose held');}}}
  if(motion&&drives&&!estop){let budget=dt*speed;for(let guard=0;motion&&guard<100&&budget>0;guard++){const m=motion.moves[motion.index],duration=Math.max(.001,m.duration),remaining=duration-motion.elapsed,step=Math.min(budget,remaining);motion.elapsed+=step;budget-=step;let t=Math.min(1,motion.elapsed/duration);if(motion.type==='taught')t=t*t*t*(10+t*(-15+6*t));angles=motion.start.map((v,i)=>v+(m.joints[i]-v)*t);arc=motion.type==='weld'&&m.arc;studio.setArc(arc);if(motion.elapsed>=duration-1e-8){motion.index++;if(motion.index>=motion.moves.length){const weld=motion.type==='weld';motion=null;arc=false;studio.setArc(false);$('#simulate').textContent='SIMULATE';status(weld?'Welding simulation complete':'Taught program complete');toast(weld?'Welding simulation complete':'Program complete');}else{motion.start=angles.slice();motion.elapsed=0;}}}}
  studio.setAngles(angles);if(cinema){const off=studio.camera.position.clone().sub(studio.orbit.target).applyAxisAngle(new T.Vector3(0,1,0),dt*.08);studio.camera.position.copy(studio.orbit.target).add(off);}
  studio.render(dt,!!jog||!!motion);viewCube.update(studio.camera.quaternion);readout+=dt;fpsTime+=dt;frames++;
  if(readout>.1){readout=0;const tcp=pose(forward(angles)),p=tcp.position.multiplyScalar(1000),r=new T.Euler().setFromQuaternion(tcp.quaternion,'YXZ'),vals=mode==='JOINT'?angles:[p.x,p.y,p.z,...[r.x,r.y,r.z].map(T.MathUtils.radToDeg)];for(let i=0;i<6;i++)$(`#joint-${i}`).textContent=vals[i].toFixed(2);$('#tcp').textContent=`X ${p.x.toFixed(1)}   Y ${p.y.toFixed(1)}   Z ${p.z.toFixed(1)}`;$('#motion').textContent=estop?'EMERGENCY STOP':arc?'WELDING':motion?'TRAVEL':jog?'MANUAL JOG':'STANDSTILL';}
  if(fpsTime>1){const size=studio.renderer.getDrawingBufferSize(new T.Vector2());$('#fps').textContent=`${Math.round(frames/fpsTime)} FPS · 3D ${size.x} × ${size.y}`;frames=0;fpsTime=0;}
  requestAnimationFrame(tick);
}
async function init(){try{studio=createStudio($('#viewport'),()=>{if(busy)return;syncPart();invalidate();},selectSeam);viewCube=createViewCube($('#view-cube'),studio.navigation);try{settings={...settingsDefaults,...JSON.parse(localStorage.getItem('estun-web-display')||'{}')};}catch{}setDisplay();await studio.loadRobot(p=>$('#load-progress').style.width=`${Math.round(p*100)}%`);$('#loading').remove();requestAnimationFrame(tick);await loadSample();api('health').then(h=>{if(h.planner?.status!=='ok')toast('CAD loaded · planning service is starting');}).catch(()=>toast('Scene ready · planning service is unavailable'));}catch(e){$('#loading-text').textContent=`Could not start the 3D workspace: ${e.message}. Reload to retry.`;console.error(e);}}
function fitWorkspace(){
  const h=$('.workspace').clientHeight-16,w=innerWidth;
  const pendantHeight=Math.max(570,$('.pendant').offsetHeight+4);
  const widthScale=Math.min(1,Math.max(.2,(w-16)/980));const prepScale=Math.min(widthScale,h/620),pendantScale=Math.min(widthScale,h/pendantHeight);
  $('.app').style.setProperty('--prep-scale',Math.max(.2,prepScale));$('.app').style.setProperty('--pendant-scale',Math.max(.2,pendantScale));
  $('.app').style.setProperty('--prep-width',`${300*Math.max(.2,prepScale)}px`);$('.app').style.setProperty('--pendant-width',`${304*Math.max(.2,pendantScale)}px`);
}
const workspaceSizing=new ResizeObserver(fitWorkspace);workspaceSizing.observe($('.workspace'));workspaceSizing.observe($('.pendant'));document.fonts.ready.then(fitWorkspace);fitWorkspace();
init();
