import './workspace.css';
import * as T from 'three';
import { createStudio } from './scene.js';
import { HOME, LIMITS, SPEEDS, forward, pose, solve } from './kinematics.js';
import { createViewCube } from './view-cube.js';
import { iconButton, displayControls } from './icons.js';
import { ProgramPlayback } from './playback.js';
import { SeamSelection, potentialSeams, seamLength } from './seam-selection.js';
import { createAngleRange } from './angle-range.js';
import { CollisionMonitor } from './collision-monitor.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const base=import.meta.env.BASE_URL;
const app=$('#app');
app.innerHTML=`<div class="app">
<header class="top"><span class="brand">ENCY HYPER <span class="brand-divider">-</span> <span class="brand-model">ESTUN</span></span></header>
<main class="workspace"><div class="viewport" id="viewport"></div>
<section class="panel prep" aria-label="Weld preparation"><div class="panel-header"><h2>Weld preparation</h2></div><div class="form stack">
<div class="row equal"><button id="import">Import STEP</button><button id="sample">Load sample</button></div><input type="file" id="file" accept=".step,.stp" hidden><div class="file-name" id="file-name">No workpiece loaded</div><hr>
<details id="placement-settings"><summary>Part placement</summary><div class="placement-body stack"><div class="row equal"><button id="move" class="active">Move · W</button><button id="rotate">Rotate · E</button></div>
<div class="coordinates"><span></span><span class="small muted">Position · mm</span><span class="small muted">Rotation · °</span>${['X','Y','Z'].map((axis,i)=>`<label>${axis}</label><input aria-label="Part ${axis} position in millimeters" id="pos-${i}" required type="number" min="-10000" max="10000" value="0" step="1"><input aria-label="Part ${axis} rotation in degrees" id="rot-${i}" required type="number" min="-360" max="360" value="0" step="1">`).join('')}</div></div></details><hr>
<div class="row spread"><h3>Potential seams</h3><span class="small muted">Angle range</span></div>
<div id="angle-range" class="angle-range"></div>
<div class="range-values"><label>Min °<input aria-label="Minimum seam angle" id="min-angle" required type="number" min="0" max="180" value="85"></label><label>Max °<input aria-label="Maximum seam angle" id="max-angle" required type="number" min="0" max="180" value="95"></label></div>
<label class="check"><input type="checkbox" id="concave"> Concave / contact only</label>
<div class="row spread small"><span>Seam length · mm</span><output id="length-summary">0 – 250</output></div>
<div class="length-ranges"><input id="min-length-range" aria-label="Minimum seam length" type="range" min="0" max="250" step="0.1" value="0"><input id="max-length-range" aria-label="Maximum seam length" type="range" min="0" max="250" step="0.1" value="250"></div>
<div class="range-values"><label>Min mm<input id="min-length" aria-label="Exact minimum seam length" required type="number" min="0" max="250" step="0.1" value="0"></label><label>Max mm<input id="max-length" aria-label="Exact maximum seam length" required type="number" min="0" max="250" step="0.1" value="250"></label></div>
<div class="row spread"><span class="small muted" id="counts">No potential seams</span></div><div class="seams" id="seams"><div class="empty">Import a STEP workpiece or load the sample to review weld seams.</div></div></div>
<div class="execution stack"><div class="row spread weaving-row"><label class="weaving-toggle"><input type="checkbox" id="weaving-enabled"> Weaving <span id="weaving-state">Off</span></label><button id="weaving-settings" title="Detailed weaving settings">Settings…</button></div>
<div id="generation" class="generation hidden" role="status"><div class="row spread"><strong id="generation-percent">0%</strong><span id="generation-time">0s</span></div><div class="progress" id="plan-progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><div id="generation-message">Preparing…</div></div>
<div class="row"><button class="primary grow" id="generate">GENERATE PROGRAM</button><button id="cancel-plan" class="hidden" title="Cancel generation">Cancel</button></div>
<div class="playback-row"><button id="simulate" disabled>Simulate</button><button id="pause" disabled title="Pause / resume">Ⅱ</button><button id="simulation-stop" disabled title="Stop and discard program">■</button></div>
<button id="export" class="hidden">Export program</button></div></section>
<div class="center-ui"><div class="telemetry"><div class="motion" id="motion">STANDSTILL</div><div id="tcp">X 927.5 &nbsp; Y 650.3 &nbsp; Z −319.0</div></div><div class="viewcube" id="view-cube"></div>
<div class="toast hidden" id="toast" role="status"></div><nav class="icon-rail" aria-label="Viewport and display">
${iconButton('axes','axes','TCP coordinate axes',true)}${iconButton('trace','trace','TCP motion trace')}${iconButton('collision-toggle','collision','Robot collision highlighting',true)}
<span class="rail-divider"></span>
${displayControls.map(([id,label])=>iconButton('setting-'+id,id,label,true)).join('')}
${iconButton('exposure-button','exposure','Exposure')}${iconButton('resolution-button','resolution','3D resolution')}${iconButton('reset-display','reset','Reset display to crisp')}
</nav>
<section id="exposure-popover" class="control-popover" popover aria-label="Exposure"><label for="exposure">Exposure <output id="exposure-value">0.92</output></label><input type="range" id="exposure" min=".4" max="1.8" step=".01" value=".92"></section>
<section id="resolution-popover" class="control-popover" popover aria-label="3D resolution"><label for="resolution">3D resolution</label><select id="resolution"><option value="1">Native · 100%</option><option value=".75">Balanced · 75%</option><option value=".5">Performance · 50%</option></select></section></div>
<aside class="pendant-dock" aria-label="Teach pendant"><div class="pendant"><i class="screw tl"></i><i class="screw tr"></i><i class="screw bl"></i><i class="screw br"></i><div class="pendant-head"><div><div class="pendant-brand">ESTUN<small>TEACH PENDANT</small></div><div class="model">S20-180 PRO</div></div><button class="estop" id="estop" aria-label="Emergency stop">↷<br>STOP</button></div>
<div class="pendant-controls"><div class="lcd"><div class="row spread small muted"><span id="drive-status">Ready</span><strong id="operation-mode">MANUAL</strong></div><div class="row modes">${['JOINT','WORLD','TOOL'].map((m,i)=>`<button class="${i?'':'active'}" data-mode="${m}">${m}</button>`).join('')}</div><div class="small muted" id="axis-caption">Axis position · degrees</div>
${Array.from({length:6},(_,i)=>`<div class="axis-row ${i?'':'selected'}" data-axis="${i}"><div class="axis-value"><span class="axis-label">J${i+1}</span><span class="value" id="joint-${i}">0.00</span><span class="unit">°</span></div><button class="jog" data-axis="${i}" data-dir="-1" aria-label="Jog axis ${i+1} negative">−</button><button class="jog" data-axis="${i}" data-dir="1" aria-label="Jog axis ${i+1} positive">+</button></div>`).join('')}</div></div>
<div class="pendant-speed"><div class="row spread"><label for="speed">Speed <span id="speed-value">25%</span></label><button class="hardware-key" id="home">Go Home</button></div><input aria-label="Speed override" id="speed" type="range" min="1" max="100" value="25"></div>
<div class="pendant-foot">SPACE STOP · ESC E-STOP</div></div></aside>
<div class="loading" id="loading"><img src="${base}assets/icon.svg" alt=""><h2>ENCY HYPER - ESTUN</h2><div class="small" id="loading-text">Loading original S20-180 Pro geometry…</div><div class="progress"><span id="load-progress"></span></div></div></main>
<footer class="footer"><span id="status">S20-180 Pro · Offline simulator · Space stops motion</span><span id="fps">WebGL 2 · Native</span></footer>
</div>
<dialog id="export-dialog"><div class="row spread"><h2>Export program</h2><button class="close" data-close aria-label="Close export">×</button></div><div class="body"><label class="export-option">Circular moves<select id="export-arcs"><option value="false">Keep circular moves</option><option value="true">Convert arcs to lines</option></select></label><label class="export-option">Torch digital output<input id="export-io" required type="number" min="0" max="65535" step="1" value="1"></label><button id="export-controller" class="primary">Robot program · Lua</button><p id="export-description" class="small"></p><div class="row equal"><button id="export-json">Trajectory JSON</button><button id="export-csv">Trajectory CSV</button></div></div></dialog>
<dialog id="weaving-dialog"><div class="row spread"><h2>Weaving settings</h2><button class="close" data-close aria-label="Close weaving settings">×</button></div><div class="body"><label class="export-option">Amplitude · mm<input id="weave-amplitude" required type="number" min="0.1" max="10" step="0.1" value="1"></label><label class="export-option">Frequency · Hz<input id="weave-frequency" required type="number" min="0.1" max="5" step="0.1" value="2"></label><label class="export-option">Plane rotation · °<input id="weave-angle" required type="number" min="-180" max="180" step="1" value="0"></label><label class="export-option">Start / end fade · mm<input id="weave-fade" required type="number" min="0.5" max="20" step="0.5" value="2"></label><p class="small">Sinusoidal motion. Amplitude is the distance from the centreline to one side. The generated path is checked before simulation and export.</p><button id="save-weaving" class="primary">Apply</button></div></dialog>
<section id="propagation" class="propagation control-popover" popover="manual"><div class="row spread"><strong id="propagation-title">Add seam</strong><button id="close-propagation" aria-label="Close propagation">×</button></div><label for="propagation-scope">Propagation</label><input id="propagation-scope" type="range" min="0" max="2" step="1" value="0"><div class="scope-labels"><span>Line</span><span>Neighbors</span><span>Contour</span></div><p id="propagation-description"></p></section>`;

let studio,viewCube,selectedScroll=false,angles=HOME.slice(),estop=false,mode='JOINT',selectedAxis=0,speed=.25,jog=null,motion=null,doc=null,partName='',selectedSeam=null,result=null,busy=false,jobId=null,revision=0,toastTimer,cinema=false,arc=false;
const selection=new SeamSelection();let completedJobId=null,angleControl=null,exporting=false,collisionMonitor=null;
const weaving={enabled:false,amplitudeMm:1,frequencyHz:2,angleDegrees:0,fadeMm:2};
const playback=new ProgramPlayback();let cancelRequested=false,operationStarted=0,operationTimer=null,operationKind='plan';
const settingsDefaults={shadows:true,ao:true,bloom:true,sparks:true,smoke:true,beads:true,exposure:.92,resolution:1};let settings={...settingsDefaults};
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
function status(text){$('#status').textContent=text;}
function discardProgram(){completedJobId=null;result=null;playback.stop();studio?.showProgram(null);refreshSeams();}
function syncControls(){
  const automatic=playback.automatic,locked=busy||automatic||estop;
  $('#operation-mode').textContent=automatic?'AUTO':'MANUAL';$('#operation-mode').classList.toggle('auto',automatic);
  $('#drive-status').textContent=estop?'STOP LATCHED':playback.state==='paused'?'Paused':automatic?'Running':'Ready';
  $('#estop').classList.toggle('latched',estop);$('#estop').setAttribute('aria-pressed',String(estop));
  $$('.jog').forEach(b=>b.disabled=locked);$('#home').disabled=locked;
  $('#simulate').disabled=busy||estop||!playback.ready;
  $('#pause').disabled=!automatic||estop;$('#pause').textContent=playback.state==='paused'?'▶':'Ⅱ';$('#pause').title=playback.state==='paused'?'Resume':'Pause';
  $('#simulation-stop').disabled=!automatic&&!result&&!motion;
  $('#generate').disabled=busy||automatic||!doc||selection.selected.size===0;$('#export').classList.toggle('hidden',!result?.program.moves.length);
  for(const id of ['import','sample','min-angle','max-angle','min-length','max-length','min-length-range','max-length-range','concave','weaving-enabled','weaving-settings','move','rotate',...Array.from({length:3},(_,i)=>`pos-${i}`),...Array.from({length:3},(_,i)=>`rot-${i}`)])$('#'+id).disabled=busy||automatic;
  $$('.seam-row button').forEach(b=>b.disabled=busy||automatic);$('#angle-range').toggleAttribute('inert',busy||automatic);$('#export').disabled=busy||automatic||exporting;
  studio?.setGizmo(!!doc&&!busy&&!automatic&&!$('.app').classList.contains('hide-prep'));
}
function stop(reason,discard=true){jog=null;motion=null;arc=false;studio?.setArc(false);if(discard)discardProgram();else if(playback.automatic)playback.stop();syncControls();if(reason){status(reason+(discard?' · generate a new program':''));toast(reason);}}
function canMove(){if(busy){toast('Wait for the current operation to finish');return false;}if(estop){toast('Press STOP again to release it');return false;}if(playback.automatic){toast('Manual jog is locked in AUTO');return false;}return true;}
function invalidate(){revision++;stop(undefined,true);studio?.clearEffects();status('Workpiece changed · generate a new program');}
function getCandidates(){if(!doc)return [];return potentialSeams(doc.seams,{minimumAngle:+$('#min-angle').value,maximumAngle:+$('#max-angle').value,minimumLength:+$('#min-length').value,maximumLength:+$('#max-length').value,concaveOnly:$('#concave').checked});}
function refreshSeams(){if(!doc)return;const list=getCandidates();$('#counts').textContent=`${list.length} potential · ${selection.selected.size} selected`;const container=$('#seams'),previousScroll=container.scrollTop;container.replaceChildren();for(const s of list){const r=result?.program.seams.find(r=>r.id===s.id),row=document.createElement('div');row.className='seam-row';const button=document.createElement('button'),included=selection.selected.has(s.id);button.className='seam-choice';button.classList.toggle('included',included);button.classList.toggle('selected',s.id===selectedSeam);button.setAttribute('aria-pressed',String(included));button.textContent=`${included?'☑':'☐'} ${s.id} · ${(seamLength(s)*1000).toFixed(1)} mm · ${s.angleDegrees.toFixed(0)}°`;if(r)button.classList.add(r.state==='Ready'?'ready':'blocked');button.title=r?.Reason||s.kind;button.onclick=e=>selectSeam(s.id,{x:e.clientX,y:e.clientY});row.append(button);container.append(row);}if(!list.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='No potential seams in the selected angle and length ranges.';container.append(empty);}container.scrollTop=previousScroll;if(selectedScroll){const button=container.querySelector('.selected');if(button){const row=button.parentElement;if(row.offsetTop<container.scrollTop)container.scrollTop=row.offsetTop;else if(row.offsetTop+row.offsetHeight>container.scrollTop+container.clientHeight)container.scrollTop=row.offsetTop+row.offsetHeight-container.clientHeight;}selectedScroll=false;}studio?.seams(list,result?.program.seams,selectedSeam,selection.selected);syncControls();}
function closePropagation(){if($('#propagation').matches(':popover-open'))$('#propagation').hidePopover();selection.finish();}
function updatePropagation(){const t=selection.transaction;if(!t)return;$('#propagation-title').textContent=`${t.adding?'Add':'Remove'} · ${t.id}`;$('#propagation-scope').value=t.scope;$('#propagation-description').textContent=[`Only the clicked line`,`Directly connected neighbors`,`Entire connected contour`][t.scope]+` · ${t.affected.size} lines`;}
function selectSeam(id,position){if(busy||playback.automatic||exporting)return;closePropagation();if(!selection.begin(id))return;selectedSeam=id;selectedScroll=true;invalidate();updatePropagation();const panel=$('#propagation'),fallback=$('#seams').getBoundingClientRect();panel.style.left=`${Math.max(8,Math.min(innerWidth-268,(position?.x??fallback.right)+12))}px`;panel.style.top=`${Math.max(8,Math.min(innerHeight-180,(position?.y??fallback.top)+8))}px`;panel.showPopover();}
function filtersChanged(){closePropagation();if(!doc)return;selection.setCandidates(getCandidates());if(!getCandidates().some(s=>s.id===selectedSeam))selectedSeam=null;invalidate();}
function syncPart(){for(let i=0;i<3;i++){$(`#pos-${i}`).value=(studio.part.position.getComponent(i)*1000).toFixed(1);$(`#rot-${i}`).value=T.MathUtils.radToDeg(studio.part.rotation.toArray()[i]).toFixed(1);}collisionMonitor?.reset();}
function acceptDocument(data,name){doc=data;partName=name;selection.reset();closePropagation();selectedSeam=null;const maxLength=Math.max(1,Math.ceil(Math.max(...data.seams.map(seamLength))*1000));for(const id of ['min-length','max-length','min-length-range','max-length-range'])$('#'+id).max=maxLength;$('#min-length').value=$('#min-length-range').value=0;$('#max-length').value=$('#max-length-range').value=maxLength;updateLengthControls();selection.setCandidates(getCandidates());studio.loadPart(data);syncPart();invalidate();$('#file-name').textContent=`${name} · STEP`;$('#file-name').title=`${data.solidCount} solids · ${data.indices.length/3} triangles`;toast(`STEP imported · ${data.solidCount} solids · ${(data.indices.length/3).toLocaleString()} triangles`);if(data.warnings?.length)status(`Import notes · ${data.warnings.join(' · ')}`);}
function setBusy(value){busy=value;syncControls();}
function progressUpdate(progress,message){const pct=Math.round(Math.max(0,Math.min(1,progress))*100);$('#generation').classList.remove('hidden');$('#generation-percent').textContent=`${pct}%`;$('#plan-progress span').style.width=`${pct}%`;$('#plan-progress').setAttribute('aria-valuenow',String(pct));$('#generation-message').textContent=message;status(message);}
function beginProgress(message){operationStarted=performance.now();clearInterval(operationTimer);operationTimer=setInterval(()=>$('#generation-time').textContent=`${((performance.now()-operationStarted)/1000).toFixed(1)}s`,200);progressUpdate(0,message);}
function endProgress(){clearInterval(operationTimer);operationTimer=null;$('#cancel-plan').classList.add('hidden');}
async function api(path,options={}){const response=await fetch(`${base}api/${path}`,options);const body=await response.json().catch(()=>({error:`Server returned ${response.status}`}));if(!response.ok)throw Error(body.error||body.message||`Request failed (${response.status})`);return body;}
async function loadSample(){if(busy)return;stop();setBusy(true);try{const r=await fetch(`${base}assets/sample.json`);if(!r.ok)throw Error('Sample could not be loaded');acceptDocument(await r.json(),'WeldingBracket');}catch(e){toast(e.message);}finally{setBusy(false);}}
async function cancelGeneration(){if(!busy)return;cancelRequested=true;$('#cancel-plan').disabled=true;progressUpdate(0,'Cancelling…');if(jobId)await api(operationKind==='import'?`imports/${jobId}`:`planner/jobs/${jobId}`,{method:'DELETE'}).catch(e=>toast(e.message));}
async function generate(){if(busy||playback.automatic||!doc)return;if(!selection.selected.size){toast('Select seams for the work order first');return;}closePropagation();stop(undefined,true);studio.clearEffects();setBusy(true);operationKind='plan';cancelRequested=false;$('#cancel-plan').disabled=false;$('#cancel-plan').classList.remove('hidden');beginProgress('Preparing robot and collision geometry…');const snapshot=revision;
  try{const response=await api('planner/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:doc,partName,partTransform:{position:[studio.part.position.x,studio.part.position.y-.12,studio.part.position.z],quaternion:studio.part.quaternion.toArray()},startAngles:angles,seamIds:[...selection.selected],minimumAngle:+$('#min-angle').value,maximumAngle:+$('#max-angle').value,minimumLengthMm:+$('#min-length').value,maximumLengthMm:+$('#max-length').value,concaveOnly:$('#concave').checked,weaving})});jobId=response.jobId;if(cancelRequested)await api(`planner/jobs/${jobId}`,{method:'DELETE'});
    for(;;){const job=await api(`planner/jobs/${jobId}`);progressUpdate(job.progress||0,job.message||'Planning trajectories…');if(job.status==='complete'){if(snapshot===revision&&!cancelRequested){result=job.result;completedJobId=jobId;playback.load(result.program);studio.showProgram(result.program);refreshSeams();progressUpdate(1,result.summary);toast(result.summary);}else progressUpdate(0,'Generation cancelled');break;}if(job.status==='failed')throw Error(job.error||job.message||'Planning failed');if(job.status==='cancelled'){progressUpdate(0,'Generation cancelled');break;}await new Promise(r=>setTimeout(r,300));}
  }catch(e){toast(e.message);progressUpdate(0,`Generation failed · ${e.message}`);}finally{jobId=null;endProgress();setBusy(false);}
}
function startSimulation(){if(busy||estop||!playback.ready)return;if(!playback.startFrom(angles)){discardProgram();syncControls();toast('Start pose changed · generate again');return;}jog=null;motion=null;studio.clearEffects();status('AUTO · simulation running');syncControls();}
function pauseSimulation(){if(playback.state==='playing'){playback.pause();arc=false;studio.setArc(false);status('AUTO · paused');}else if(playback.state==='paused'){playback.resume();status('AUTO · simulation running');}syncControls();}
function startJog(axis,dir){if(!canMove())return;stop(undefined,true);jog={axis,dir};selectedAxis=axis;selectAxis();}
function selectAxis(){$$('.axis-row').forEach((el,i)=>el.classList.toggle('selected',i===selectedAxis));}
function setMode(value){jog=null;mode=value;$$('[data-mode]').forEach(el=>el.classList.toggle('active',el.dataset.mode===mode));$('#axis-caption').textContent=mode==='JOINT'?'Axis position · degrees':'TCP position · mm / degrees';$$('.axis-row').forEach((el,i)=>{el.querySelector('.axis-label').textContent=mode==='JOINT'?`J${i+1}`:'XYZABC'[i];el.querySelector('.unit').textContent=mode==='JOINT'||i>2?'°':'mm';});}
function setGizmo(mode){studio.setMode(mode);$('#move').classList.toggle('active',mode==='translate');$('#rotate').classList.toggle('active',mode==='rotate');}
function toggleDock(which){const root=$('.app');root.classList.toggle(`hide-${which}`);syncControls();}
function download(data,name,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setDisplay(){for(const [k] of displayControls){const button=$(`#setting-${k}`);button.classList.toggle('active',settings[k]);button.setAttribute('aria-pressed',String(settings[k]));}$('#exposure').value=settings.exposure;$('#exposure-value').textContent=Number(settings.exposure).toFixed(2);$('#exposure-button').title=`Exposure · ${Number(settings.exposure).toFixed(2)}`;$('#resolution').value=settings.resolution;$('#resolution-button').title=`3D resolution · ${Math.round(settings.resolution*100)}%`;studio?.applySettings(settings);try{localStorage.setItem('estun-web-display',JSON.stringify(settings));}catch{}}
function emergency(){stop('Emergency stop latched');estop=true;syncControls();}
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||busy||playback.automatic)return;if(file.size>64*1024*1024){toast('Browser import limit: 64 MB');return;}stop();setBusy(true);operationKind='import';cancelRequested=false;$('#cancel-plan').disabled=false;$('#cancel-plan').classList.remove('hidden');beginProgress('Uploading STEP geometry…');try{const data=new FormData();data.append('file',file);const raw=await api('import',{method:'POST',body:data});jobId=raw.jobId;if(cancelRequested)await api(`imports/${jobId}`,{method:'DELETE'});for(;;){const job=await api(`imports/${jobId}`);progressUpdate(job.progress,job.message);if(job.status==='complete'){if(!cancelRequested){acceptDocument(job.result.document,job.result.name);progressUpdate(1,`Imported in ${job.result.timing.seconds.toFixed(2)}s${job.result.timing.cached?' · cached geometry':''}`);}break;}if(job.status==='failed')throw Error(job.error);if(job.status==='cancelled'){progressUpdate(0,'Import cancelled');break;}await new Promise(r=>setTimeout(r,250));}}catch(error){toast(error.message);progressUpdate(0,`Import failed · ${error.message}`);}finally{jobId=null;endProgress();setBusy(false);}};
$('#sample').onclick=loadSample;$('#generate').onclick=generate;$('#cancel-plan').onclick=cancelGeneration;$('#simulate').onclick=startSimulation;$('#pause').onclick=pauseSimulation;$('#simulation-stop').onclick=()=>stop('Simulation stopped · replan required');
$('#move').onclick=()=>setGizmo('translate');$('#rotate').onclick=()=>setGizmo('rotate');
for(let i=0;i<3;i++)for(const kind of ['pos','rot'])$(`#${kind}-${i}`).onchange=e=>{if(!doc||busy||playback.automatic)return;const v=Number(e.target.value),limit=kind==='pos'?10000:360;if(!Number.isFinite(v)||Math.abs(v)>limit){syncPart();return;}if(kind==='pos')studio.part.position.setComponent(i,v*.001);else{const r=studio.part.rotation.toArray();r[i]=T.MathUtils.degToRad(v);studio.part.rotation.fromArray(r);}collisionMonitor?.reset();invalidate();};
for(const id of ['min-angle','max-angle'])$('#'+id).onchange=()=>{const min=$('#min-angle'),max=$('#max-angle');min.value=Math.max(0,Math.min(180,+min.value));max.value=Math.max(0,Math.min(180,+max.value));if(+min.value>+max.value){if(id==='min-angle')max.value=min.value;else min.value=max.value;}angleControl.update();filtersChanged();};$('#concave').onchange=filtersChanged;
function updateLengthControls(){const min=+$('#min-length').value,max=+$('#max-length').value;$('#min-length-range').value=min;$('#max-length-range').value=max;$('#length-summary').textContent=`${min.toFixed(1)} – ${max.toFixed(1)}`;}
for(const id of ['min-length','max-length','min-length-range','max-length-range'])$('#'+id)[id.endsWith('-range')?'oninput':'onchange']=()=>{const lower=id.startsWith('min'),input=$('#'+id),bound=lower?$('#min-length'):$('#max-length');bound.value=Math.max(0,Math.min(+input.max,+input.value));if(+$('#min-length').value>+$('#max-length').value){if(lower)$('#max-length').value=bound.value;else $('#min-length').value=bound.value;}updateLengthControls();filtersChanged();};
$('#propagation-scope').oninput=e=>{selection.applyScope(+e.target.value);invalidate();updatePropagation();};$('#close-propagation').onclick=closePropagation;
document.addEventListener('pointerdown',e=>{if($('#propagation').matches(':popover-open')&&!$('#propagation').contains(e.target)&&!e.target.closest('.seam-choice')&&!e.target.closest('#viewport'))closePropagation();});
$('#weaving-enabled').onchange=e=>{weaving.enabled=e.target.checked;$('#weaving-state').textContent=weaving.enabled?'On':'Off';invalidate();};$('#weaving-settings').onclick=()=>{for(const [id,key] of [['amplitude','amplitudeMm'],['frequency','frequencyHz'],['angle','angleDegrees'],['fade','fadeMm']])$('#weave-'+id).value=weaving[key];$('#weaving-dialog').showModal();};$('#save-weaving').onclick=()=>{const fields=[['amplitude','amplitudeMm'],['frequency','frequencyHz'],['angle','angleDegrees'],['fade','fadeMm']];for(const [id] of fields)if(!$('#weave-'+id).reportValidity())return;for(const [id,key] of fields)weaving[key]=+$('#weave-'+id).value;$('#weaving-dialog').close();invalidate();};
$('#estop').onclick=()=>{if(estop){estop=false;syncControls();toast('STOP released · MANUAL');}else emergency();};
$('#home').onclick=()=>{if(!canMove())return;stop(undefined,true);motion={elapsed:0,start:angles.slice(),duration:Math.max(.4,...angles.map((a,i)=>Math.abs(a-HOME[i])/SPEEDS[i]))};syncControls();};
$('#speed').oninput=e=>{speed=Number(e.target.value)/100;$('#speed-value').textContent=`${Math.round(speed*100)}%`;};
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('.axis-value').forEach((el,i)=>el.onclick=()=>{selectedAxis=i;selectAxis();});
$$('.jog').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);startJog(Number(b.dataset.axis),Number(b.dataset.dir));};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{jog=null;};});
$('#export').onclick=()=>{if(!result){toast('Generate a welding program first');return;}$('#export-description').textContent=result.controller?.description||'Robot program from the supplied command reference. Tool and coordinate calibration must match the cell.';$('#export-controller').disabled=!result.controller?.text;$('#export-dialog').showModal();};$('#export-json').onclick=()=>{if(result)download(JSON.stringify(result.program,null,2),`${partName}-weld.json`);};$('#export-csv').onclick=()=>{if(result)download(result.csv,`${partName}-weld.csv`,'text/csv');};
$('#export-controller').onclick=async()=>{if(!result||!completedJobId||exporting)return;if(!$('#export-io').reportValidity())return;exporting=true;$('#export-controller').disabled=true;$('#export-controller').textContent='Preparing export…';const planId=completedJobId;try{const job=await api(`planner/jobs/${planId}/export`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({linearizeArcs:$('#export-arcs').value==='true',torchDigitalOutput:+$('#export-io').value})});for(;;){const state=await api(`planner/jobs/${job.jobId}`);if(state.status==='complete'){const exported=state.result;if(completedJobId===planId){const previousState=playback.state;result=exported;playback.load(exported.program);if(previousState==='complete')playback.state='complete';studio.showProgram(exported.program);refreshSeams();}download(exported.controller?.text??exported.text,exported.controller?.fileName??exported.fileName??'ency-hyper-estun.lua','text/plain');break;}if(state.status==='failed'||state.status==='cancelled')throw Error(state.error||state.message);await new Promise(r=>setTimeout(r,200));}}catch(e){toast(e.message);}finally{exporting=false;$('#export-controller').disabled=false;$('#export-controller').textContent='Robot program · Lua';syncControls();}};
$('#collision-toggle').onclick=e=>{const enabled=!e.currentTarget.classList.contains('active');e.currentTarget.classList.toggle('active',enabled);e.currentTarget.setAttribute('aria-pressed',String(enabled));collisionMonitor?.setEnabled(enabled);};
for(const [id,method] of [['axes','setAxes'],['trace','setTrace']])$('#'+id).onclick=e=>{const button=e.currentTarget;button.classList.toggle('active');const active=button.classList.contains('active');button.setAttribute('aria-pressed',String(active));studio[method](active);};
for(const id of ['exposure','resolution']){
  const button=$('#'+id+'-button'),panel=$('#'+id+'-popover');button.onclick=()=>{const rect=button.getBoundingClientRect();panel.style.left=`${Math.max(8,Math.min(innerWidth-228,rect.right+8))}px`;panel.style.top=`${Math.max(8,Math.min(innerHeight-104,rect.top))}px`;panel.togglePopover();};
}
function toggleCinema(){cinema=!cinema;$('.app').classList.toggle('cinema',cinema);studio.setGizmo(!cinema&&!!doc&&!busy&&!playback.automatic&&!$('.app').classList.contains('hide-prep'));}
for(const [key] of displayControls)$(`#setting-${key}`).onclick=()=>{settings[key]=!settings[key];setDisplay();};$('#exposure').oninput=e=>{settings.exposure=+e.target.value;setDisplay();};$('#resolution').onchange=e=>{settings.resolution=+e.target.value;setDisplay();};$('#reset-display').onclick=()=>{settings={...settingsDefaults};setDisplay();};
function focusLost(){jog=null;if(playback.state==='playing'){playback.pause();arc=false;studio?.setArc(false);status('AUTO · paused while inactive');syncControls();}else if(motion)stop('Motion stopped · window lost focus');}window.addEventListener('blur',focusLost);document.addEventListener('visibilitychange',()=>{if(document.hidden)focusLost();});
window.addEventListener('keydown',e=>{const edit=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(e.code==='Escape'){emergency();return;}if(edit||$('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();stop('Motion stopped');}if(e.repeat)return;if(e.code==='KeyF')studio?.fit();if(e.code==='KeyP')toggleDock('pendant');if(e.code==='KeyW')setGizmo('translate');if(e.code==='KeyE')setGizmo('rotate');if(e.code==='Tab'){e.preventDefault();toggleCinema();}if(e.code==='ArrowUp'||e.code==='ArrowDown'){e.preventDefault();selectedAxis=(selectedAxis+(e.code==='ArrowDown'?1:5))%6;selectAxis();}if(e.code==='ArrowLeft'||e.code==='ArrowRight'){e.preventDefault();startJog(selectedAxis,e.code==='ArrowRight'?1:-1);}if(e.code==='Delete'&&selectedSeam&&!busy&&!playback.automatic&&selection.selected.has(selectedSeam))selectSeam(selectedSeam);});window.addEventListener('keyup',e=>{if(e.code==='ArrowLeft'||e.code==='ArrowRight')jog=null;});

let last=performance.now(),readout=0,frames=0,fpsTime=0;
function tick(now){const dt=Math.min((now-last)/1000,.05);last=now;
  if(jog&&!estop&&!busy&&!playback.automatic){const {axis,dir}=jog;if(mode==='JOINT')angles[axis]=T.MathUtils.clamp(angles[axis]+dir*SPEEDS[axis]*speed*dt,-LIMITS[axis],LIMITS[axis]);else{const target=forward(angles),p=pose(target),direction=new T.Vector3().setComponent(axis%3,1),dp=axis<3?.25*speed*dt:0,da=axis>=3?Math.PI/3*speed*dt:0;if(mode==='TOOL')direction.applyQuaternion(p.quaternion);if(axis<3){p.position.addScaledVector(direction,dir*dp);target.setPosition(p.position);}else{p.quaternion.premultiply(new T.Quaternion().setFromAxisAngle(direction,dir*da));target.compose(p.position,p.quaternion,new T.Vector3(1,1,1));}const a=solve(target,angles,Math.max(.000015,dp*.12),Math.max(.00008,da*.12));if(a){let factor=1;for(let i=0;i<6;i++){const diff=Math.abs(a[i]-angles[i]);if(diff>1e-6)factor=Math.min(factor,SPEEDS[i]*speed*dt/diff);}if(factor>.015)angles=angles.map((v,i)=>v+(a[i]-v)*factor);else{jog=null;toast('TCP jog limited near singularity');}}else{jog=null;toast('TCP limit reached · pose held');}}}
  if(motion&&!estop&&!busy){motion.elapsed+=dt*speed;let t=Math.min(1,motion.elapsed/motion.duration);t=t*t*t*(10+t*(-15+6*t));angles=motion.start.map((v,i)=>v+(HOME[i]-v)*t);if(t>=1){motion=null;syncControls();status('MANUAL · home reached');}}
  const wasAutomatic=playback.automatic,next=playback.tick(dt,speed);if(next)angles=next;arc=playback.arc;studio.setArc(arc);if(wasAutomatic&&!playback.automatic){status('Simulation complete · MANUAL');toast('Simulation complete');syncControls();}
  studio.setAngles(angles);if(cinema){const off=studio.camera.position.clone().sub(studio.orbit.target).applyAxisAngle(new T.Vector3(0,1,0),dt*.08);studio.camera.position.copy(studio.orbit.target).add(off);}
  studio.render(dt,!!jog||!!motion||playback.state==='playing');viewCube.update(studio.camera.quaternion);collisionMonitor?.tick(angles,doc,doc?{position:[studio.part.position.x,studio.part.position.y-.12,studio.part.position.z],quaternion:studio.part.quaternion.toArray()}:undefined,now,busy||exporting);readout+=dt;fpsTime+=dt;frames++;
  if(readout>.1){readout=0;const tcp=pose(forward(angles)),p=tcp.position.multiplyScalar(1000),r=new T.Euler().setFromQuaternion(tcp.quaternion,'YXZ'),vals=mode==='JOINT'?angles:[p.x,p.y,p.z,...[r.x,r.y,r.z].map(T.MathUtils.radToDeg)];for(let i=0;i<6;i++)$(`#joint-${i}`).textContent=vals[i].toFixed(2);$('#tcp').textContent=`X ${p.x.toFixed(1)}   Y ${p.y.toFixed(1)}   Z ${p.z.toFixed(1)}`;$('#motion').textContent=estop?'EMERGENCY STOP':arc?'WELDING':playback.state==='paused'?'PAUSED':playback.state==='playing'?'AUTO · TRAVEL':motion?'GO HOME':jog?'MANUAL JOG':'STANDSTILL';}
  if(fpsTime>1){const size=studio.renderer.getDrawingBufferSize(new T.Vector2());$('#fps').textContent=`${Math.round(frames/fpsTime)} FPS · 3D ${size.x} × ${size.y}`;frames=0;fpsTime=0;}
  requestAnimationFrame(tick);
}
async function init(){try{studio=createStudio($('#viewport'),()=>{if(busy||playback.automatic)return;syncPart();invalidate();},selectSeam);viewCube=createViewCube($('#view-cube'),studio.navigation);collisionMonitor=new CollisionMonitor(body=>api('planner/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),(links,check)=>{studio.showCollisions(links);const button=$('#collision-toggle');button.classList.toggle('collision-hit',links.length>0);button.title=check?.unavailable?'Collision display unavailable':links.length?check.reason:'Robot collision highlighting · adjacent joints ignored';});try{settings={...settingsDefaults,...JSON.parse(localStorage.getItem('estun-web-display')||'{}')};}catch{}setDisplay();await studio.loadRobot(p=>$('#load-progress').style.width=`${Math.round(p*100)}%`);$('#loading').remove();requestAnimationFrame(tick);await loadSample();api('health').then(h=>{if(h.planner?.status!=='ok')toast('CAD loaded · planning service is starting');}).catch(()=>toast('Scene ready · planning service is unavailable'));}catch(e){$('#loading-text').textContent=`Could not start the 3D workspace: ${e.message}. Reload to retry.`;console.error(e);}}
function fitWorkspace(){
  const h=$('.workspace').clientHeight-16,w=innerWidth;
  const pendantHeight=Math.max(570,$('.pendant').offsetHeight+4);
  const form=$('.prep .form'),formStyles=getComputedStyle(form),gap=parseFloat(formStyles.gap)||0;
  const fixed=[...form.children].filter(el=>el.id!=='seams'&&getComputedStyle(el).display!=='none');
  const prepHeight=Math.max(600,fixed.reduce((sum,el)=>sum+el.offsetHeight,0)+gap*fixed.length+$('.prep .panel-header').offsetHeight+$('.execution').offsetHeight+122);
  const widthScale=Math.min(1,Math.max(.2,(w-16)/980));const prepScale=Math.min(widthScale,h/prepHeight),pendantScale=Math.min(widthScale,h/pendantHeight);
  $('.app').style.setProperty('--prep-scale',Math.max(.2,prepScale));$('.app').style.setProperty('--pendant-scale',Math.max(.2,pendantScale));
  $('.app').style.setProperty('--prep-width',`${300*Math.max(.2,prepScale)}px`);$('.app').style.setProperty('--pendant-width',`${304*Math.max(.2,pendantScale)}px`);
}
$('#placement-settings').addEventListener('toggle',fitWorkspace);
angleControl=createAngleRange($('#angle-range'),$('#min-angle'),$('#max-angle'),filtersChanged);
const workspaceSizing=new ResizeObserver(fitWorkspace);workspaceSizing.observe($('.workspace'));workspaceSizing.observe($('.pendant'));workspaceSizing.observe($('.execution'));document.fonts.ready.then(fitWorkspace);fitWorkspace();syncControls();
init();
